development:
  adapter: sqlite3
  database: db/movies_development.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/movies_test.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/movies_production.db
  pool: 5
  timeout: 5000 